openapi: 3.0.3
info:
  title: Frase Certa API
  version: 1.0.0
  description: >
    Frase Certa API é uma API leve e moderna para fornecer frases motivacionais e inspiradoras em dois idiomas: português e inglês. Ideal para integrar com sites, apps, chatbots e projetos que desejam impactar positivamente seus usuários com palavras de incentivo.

servers:
  - url: https://frasecertaapi-680953228709.us-central1.run.app
    description: Servidor em produção (Cloud Run)

tags:
  - name: Frases
    description: Endpoints para frases aleatórias, listagem e busca
  - name: Autores
    description: Endpoints relacionados a autores únicos
  - name: Estatísticas
    description: Informações sobre a quantidade de frases disponíveis

paths:
  /frase:
    get:
      tags:
        - Frases
      summary: Obter frase aleatória
      description: Retorna uma frase aleatória e seu autor, com suporte a tradução opcional para português.
      parameters:
        - in: query
          name: lang
          schema:
            type: string
            enum: [en, pt]
            default: en
          description: Idioma da frase. Aceita "en" (inglês) ou "pt" (português).
      responses:
        200:
          description: Frase aleatória obtida com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  frase:
                    type: string
                  autor:
                    type: string

  /frases:
    get:
      tags:
        - Frases
      summary: Listar todas as frases com paginação
      description: >
        Lista todas as frases disponíveis no JSON com suporte a paginação.
        Caso lang=pt seja informado, a resposta incluirá um aviso de que as frases estão em inglês.
      parameters:
        - in: query
          name: pagina
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Número da página
        - in: query
          name: limite
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 5
          description: Quantidade de frases por página
        - in: query
          name: lang
          schema:
            type: string
            enum: [en, pt]
            default: en
          description: Idioma da resposta. Apenas "en" é traduzido. "pt" retornará aviso.
      responses:
        200:
          description: Lista de frases retornada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  pagina:
                    type: integer
                  limite:
                    type: integer
                  resultados:
                    type: array
                    items:
                      type: object
                      properties:
                        quoteText:
                          type: string
                        quoteAuthor:
                          type: string
                  aviso:
                    type: string
                    description: Exibido apenas se lang for diferente de "en"

  /frases/autor/{nome}:
    get:
      tags:
        - Frases
      summary: Listar frases por autor
      description: >
        Retorna uma lista de frases que contenham o nome (ou parte dele) do autor especificado. Busca case-insensitive.
      parameters:
        - name: nome
          in: path
          required: true
          schema:
            type: string
          description: Nome parcial ou completo do autor
      responses:
        200:
          description: Frases do autor retornadas com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    quoteText:
                      type: string
                    quoteAuthor:
                      type: string
        404:
          description: Nenhuma frase encontrada para o autor

  /autores:
    get:
      tags:
        - Autores
      summary: Listar autores únicos
      description: Retorna todos os autores únicos presentes no arquivo de frases.
      responses:
        200:
          description: Lista de autores retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /frase/busca/{palavra}:
    get:
      tags:
        - Frases
      summary: Buscar frases por palavra-chave
      description: >
        Retorna todas as frases que contenham a palavra especificada.
        A busca é realizada apenas nas frases em inglês (não traduzidas).
      parameters:
        - name: palavra
          in: path
          required: true
          schema:
            type: string
          description: Palavra-chave a ser buscada no conteúdo da frase (em inglês)
      responses:
        200:
          description: Frases encontradas com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  aviso:
                    type: string
                    example: A busca é feita apenas em frases em inglês. Traduções automáticas não são suportadas.
                  resultados:
                    type: array
                    items:
                      type: object
                      properties:
                        quoteText:
                          type: string
                        quoteAuthor:
                          type: string
        404:
          description: Nenhuma frase encontrada com a palavra informada
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                    example: Nenhuma frase contém a palavra: coragem
                  aviso:
                    type: string
                    example: A busca é feita apenas em frases em inglês. Traduções automáticas não são suportadas.

  /frases/quantidade:
    get:
      tags:
        - Estatísticas
      summary: Contar frases totais
      description: Retorna a quantidade total de frases disponíveis no arquivo JSON.
      responses:
        200:
          description: Quantidade total retornada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
